### ISSUE TITLE
Refactor fortunes.json

### ISSUE THREAD

**Issue by JaredJose** [cse110-sp23-group25/tarot-cards#15]
Reconfigure the fortunes.json file to be more structured. More specifically, utilize arrays/objects rather than have a separate object for each card's interpretation.

**Comment by amtjitro** [comment]
<img width="627" alt="Screenshot 2023-06-03 at 7 13 09 PM" src="https://github.com/cse110-sp23-group25/tarot-cards/assets/60487970/52ef2c9e-ce99-499e-8a0a-86562b3808c8">
