### ISSUE TITLE
Create deck/cards Classes

### ISSUE THREAD

**Issue by JaredJose** [cse110-sp23-group25/tarot-cards#16]
In order to make the javascript aspect of this project more testable/documentable, we must refactor our code to utilize a deck object which contains cards objects. This will also allow us in the future to more easily change the source of our cards assets.

**Comment by amtjitro** [comment]
<img width="627" alt="Screenshot 2023-06-03 at 7 13 37 PM" src="https://github.com/cse110-sp23-group25/tarot-cards/assets/60487970/c7afb84f-ca35-4e6f-b791-be5481439968">
