### ISSUE TITLE
"world" tarot card sizing

### ISSUE THREAD

**Issue by amtjitro** [cse110-sp23-group25/tarot-cards#30]
Re-generate the world tarot card. It does not fit well with the other tarot cards as it is too wide and it gets cut off.

**Comment by kaleemullah786** [comment]
hey, I would like to work on this. can you provide more details

**Comment by NickAzp** [comment]
![image](https://github.com/cse110-sp23-group25/tarot-cards/assets/69650461/a1f233ae-7779-40ac-853f-6ba76dda2055)
